### ISSUE TITLE
Does not work with ESLint v5

### ISSUE THREAD

**Issue by revelt** [avajs/eslint-plugin-ava#195]
hi all,

As you know, ESLint v.5 was released recently. I just updated all the dependencies and started to get ESLint error message:

```
/Users/royston/Documents/__PROJECTS/____libs/ranges-invert/src/main.js
  3:1  error  Parsing error: Unexpected token import

/Users/royston/Documents/__PROJECTS/____libs/ranges-invert/test/test.js
  1:1  error  Parsing error: Unexpected token import

✖ 2 problems (2 errors, 0 warnings)
```

Investigating further, I discovered that old `.eslintrc` will work OK if I remove `"ava"` from  `"plugins": [...]` (and all the `ava-` rules). I think something needs to be updated in this plugin to support ESLint `v.5`.

Please add support for the latest ESLint. If you want some code to test, here's the repo in question: https://bitbucket.org/codsen/ranges-invert/ (I moved it to Bitbucket because Github cashed-in on our open source work).

Thank you.

**Comment by freaktechnik** [comment]
I made the observation that even just loading the ava plugin breaks eslint 5, even without any active rules.

So all you need to reproduce this is an eslint config that looks like this:
```json
{
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "plugins": [ "ava" ]
}
```

**Comment by ronen** [comment]
FYI, confirming this failure with the latest release of eslint-plugin-ava (4.2.1).  Thanks

**Comment by novemberborn** [comment]
Looks like this was fixed in 07cb69971450920ab8402a721401f1b209353304. Will try and get a release out soon.

**Comment by novemberborn** [comment]
New release is out!

**Comment by freaktechnik** [comment]
Hm, this release has not fixed the issue for me. I still get this error with the configuration I posted above.

**Comment by novemberborn** [comment]
@freaktechnik if you could share an isolated reproduction that'd be great. I tried to reproduce the problem a few days ago and couldn't when using `master`.

**Comment by freaktechnik** [comment]
It seems that having an older version of espree with higher priority installed (like `"espree": "3.4.1"` as dev dependency) will break the plugin. I assume it's trying to use the wrong espree. Which may well be an npm/node issue? I see the correct espree installed into the node_modules folder of the eslint-plugin-ava. Note that the ancient espree is completely unused, well unless somehow eslint ends up using it.

The dev deps that break it for me:
```json
"devDependencies": {
    "eslint": "^5.1.0",
    "eslint-plugin-ava": "^5.0.0",
    "espree": "3.4.1"
  },
```

I'll remove the dependency in my setup that includes this ancient version of espree, as it's not that important to me.
